name: Trigger auto deployment for asdf

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/asdf-AutoDeployTrigger-2f6e0adc-8b83-4312-a77a-5674ec5ad6b7.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ASDF_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ASDF_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ASDF_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: recon.offensi.com
          registryUsername: ${{ secrets.ASDF_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ASDF_REGISTRY_PASSWORD }}
          containerAppName: asdf
          resourceGroup: DefaultResourceGroup-CAU
          imageToBuild: recon.offensi.com/asdf:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


